# Generated by Django 5.2.8 on 2025-11-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to='profile_pics/'),
        ),
    ]
