# Generated by Django 5.2.8 on 2025-12-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
