# Generated by Django 5.2.8 on 2025-12-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_productimages_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Adress'},
        ),
    ]
