# Generated by Django 5.2.8 on 2026-01-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
