# Generated by Django 5.2.8 on 2026-01-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
