# Generated by Django 5.2.8 on 2026-01-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_orderitem_image_id_orderitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, null=True),
        ),
    ]
